[platformio]
default_envs = 
	esp32dev
src_dir = .
include_dir = .
extra_configs =
  platformio_override.ini

[env]
lib_deps =
	adafruit/DHT sensor library@^1.4.7
	fbiego/ESP32Time@^2.0.6
	esp32async/AsyncTCP@^3.5.0
	esp32async/ESPAsyncWebServer@^3.12.0
	gyverlibs/GyverOLED@^1.6.4
	mathertel/RotaryEncoder@^1.6.0


[env:esp32dev]
; Arduino 3.3.11 IDF 5.5.5
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.311/platform-espressif32.zip
board = esp32dev
framework = arduino
monitor_speed = 115200

build_flags =
    -Wfatal-errors
	-DRELEASE_NAME=\"TauPunktLuefter\"

lib_deps =
	${env.lib_deps}

extra_scripts = 
	pre:pio-scripts/check_config.py
    post:pio-scripts/output_bins.py
